language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

services:
  - docker

addons:
  apt:
    sources:
    packages:
      # Getting compile errors on javac 1.8.0_31-b13
      - oracle-java8-installer

install: "mvn clean deploy --settings settings.xml -Pstaging"